### ISSUE TITLE
スマホでもスタイルが崩れないようにしたい

### ISSUE THREAD

**Issue by yutokyokutyo** [MICS-NAGOYA/application#3]
![image](https://user-images.githubusercontent.com/7356977/50752350-4ba25b00-1291-11e9-9087-c14a5461b168.png)

## 理想
![image](https://user-images.githubusercontent.com/7356977/50752382-6bd21a00-1291-11e9-8845-35041f03e632.png)

**Comment by yutokyokutyo** [comment]
トグルを使いたくない。
https://cccabinet.jpn.org/bootstrap4/components/navbar
navbar のsample実装にはこの問題を解決させる方法の記述なし

そもそもnavbarを使わないほうがいいのかな。

**Comment by yutokyokutyo** [comment]
ref: http://blog.shuffleee.com/2790/
これも適用されない。あまり分かってないなぁ。

```css
  /* --- navigationBar --- */
  .navbar-toggle {
      display: none;
  }
  .collapse {
      display: block;
      border-color:transparent;
  }
  .navbar-right {
      float: right;
  }
  .navbar-header {
      float: left;
  }
  .navbar-nav {
      margin:0 -15px 0 0;
  }
  .navbar-nav>li>a {
      padding-top: 15px;
      padding-bottom: 15px;
  }
```

多分もうこれトグルは無効化されてるので、CSSでいい感じに書けば終わるのでは？
